spring:
  application:
    name: spring-zuul-gateway
server:
  port: 8889

zuul:
  routes:
    tests:
      path: /api/front/test/**
      url: http://localhost:8091/
      stripPrefix: false
    api-01:
      path: /prod/**
      serviceId: eureka-provider
      stripPrefix: true
  strip-prefix: false
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
