server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: 127.0.0.1
spring:
  application:
    name: eureka-server.01
  security:
    user:
      name: admin
      password: admin
