eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
spring:
  application:
    name: feign-consumer
server:
  port: 9000
feign:
  hystrix:
    enabled: true