spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sdw2330976/config-repo
          search-paths: repo
          default-label: master
#          username:
#          password:
  profiles:
    active: dev
server:
  port: 8888
